CREATE DATABASE brokenlinksfinder;

CREATE TABLE  `requests` (
`Id` INT NOT NULL AUTO_INCREMENT ,
`IP` VARCHAR( 64 ) NOT NULL ,
`Url` TEXT NOT NULL ,
`Email` VARCHAR(100) NOT NULL,
`StartTime` DATETIME NOT NULL ,
`EndTime` DATETIME,
PRIMARY KEY (  `Id` )
) ENGINE = INNODB;